---
- hosts: localhost
  connection: local
  strategy: debug
  vars:
    ssh_key: nginx
    num_nodes: 2
    security_group_name: nginx
    template: Linux Debian 9 64-bit
    template_filter: featured
    instance_type: Micro
    root_disk_size: 10
    zone: ch-gva-2

  roles:
    - common
    - infra
