
---
- hosts: localhost
  connection: local
  vars:
    ssh_key: bitcoin-congestion-manager
    num_nodes: 1
    security_group_name: bitcoin-congestion-manager
    nodes: bitcoin-congestion-manager_nodes
    template: Linux Ubuntu 16.04 LTS 64-bit
    template_filter: featured
    instance_type: Medium
    root_disk_size: 200
    zone: ch-gva-2

  roles:
    - common
    - infra
