---
- hosts: [lighttpd_nodes]
  remote_user: root
  roles:
    - nodesource.node

  tasks:
    - name: Install lighttpd web server
      apt: name=lighttpd state=latest update_cache=true

    - name: Install supervisord
      apt: name=supervisor state=latest update_cache=true

    - name: Install python3-pip
      apt: name=python3-pip state=latest update_cache=true

    - name: Install crossbar
      pip:
        name: crossbar

    # - name: Install express
    #   npm:
    #     name: express
    #     state: latest
    #     path: /express
