  - name: Create instances
    local_action:
      module: cs_instance
      display_name: "{{security_group_name}}{{ item }}"
      template: "{{ template }}"
      service_offering: "{{ instance_type }}"
      ssh_key: "{{ ssh_key }}"
      security_groups: [ '{{ security_group_name }}' ]
      zone: "{{ zone }}"
      root_disk_size: "{{ root_disk_size }}"
    with_sequence: count={{ num_nodes }}
    register: nodes

  # - name: show VM IP
  #   debug: msg="{% for item in nodes.results %}{{ item.default_ip }}{% endfor %}"

  # - name: assing IP to the inventory
  #   set_fact: ansible_ssh_host="{% for item in nodes.results %}{{ item.default_ip }}{% endfor %}"




  # - name: dbg
  #   debug: msg="{{ ansible_ssh_host }}"
    # - name: assing IP to the inventory
    # set_fact: ansible_ssh_host={{ nodes.default_ip }}
